-- Prophecy ritual: tarot-like deck of forward-looking cards generated by the
-- taste pipeline. Members draw 3 cards that become their public statement.
--
-- See design-mockups/milestones-and-prophecy-plan.md for the full plan.

ALTER TABLE builder_profiles
  ADD COLUMN IF NOT EXISTS prophecy_deck jsonb,
  ADD COLUMN IF NOT EXISTS prophecy_chosen jsonb,
  ADD COLUMN IF NOT EXISTS prophecy_drawn_at timestamptz,
  ADD COLUMN IF NOT EXISTS show_prophecy boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN builder_profiles.prophecy_deck IS
  'Full AI-generated deck: { field: [...], method: [...], audience: [...], arc: [...] }. Written by pipeline; read by reveal UI.';
COMMENT ON COLUMN builder_profiles.prophecy_chosen IS
  'Array of 3 card objects the member picked. Becomes the public prophecy statement.';
COMMENT ON COLUMN builder_profiles.prophecy_drawn_at IS
  'Timestamp of the member''s last pick — used to gate the 60-day redraw window.';
